# SPDX-License-Identifier: Apache-2.0
"""CI staleness gate for the generated config/CLI references (issue athenaeum#1424).

``docs/reference/configuration.md`` and ``docs/reference/cli.md`` are GENERATED
(by ``scripts/gen_config_reference.py`` / ``scripts/gen_cli_reference.py``) from
``athenaeum.config``'s ``resolve_*`` functions and ``athenaeum.cli.build_parser()``'s
real argparse tree, respectively. This module is the CI gate that makes drift
between the generated text and the committed file a build failure, following
the exact pattern the three narrower doc-parity gates already established:

- ``tests/test_exit_codes_doc_parity.py`` — pins a doc, derives the real answer
  from source, asserts equality, and proves the derivation is non-trivial with
  a synthetic fixture.
- ``tests/test_env_docs.py`` — drives a `scripts/*.py` checker exactly the way
  CI does.
- ``tests/test_measurement_docs.py`` — pins a generated doc and asserts it
  matches what the generator produces.

``TestLiveTreeParity`` is the REAL CI gate (regenerate, compare bytes to what's
committed). ``TestGenerationIsGenuine`` proves the generators are not
degenerate — i.e. not "hardcode-and-echo-back-the-committed-file" — by
monkeypatching the introspected source (a throwaway ``resolve_*`` function; a
throwaway CLI flag) and asserting the generated text actually changes to
reflect it. ``TestGenerationIsDeterministic`` proves regeneration is
byte-stable across repeated calls, which is what makes the gate trustworthy
rather than flaky.
"""

from __future__ import annotations

import importlib.util
import os
import time
from pathlib import Path
from typing import Any

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
CONFIG_REFERENCE_DOC = REPO_ROOT / "docs" / "reference" / "configuration.md"
CLI_REFERENCE_DOC = REPO_ROOT / "docs" / "reference" / "cli.md"


def _load_script(name: str):
    path = REPO_ROOT / "scripts" / f"{name}.py"
    spec = importlib.util.spec_from_file_location(name, path)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


gen_config_reference = _load_script("gen_config_reference")
gen_cli_reference = _load_script("gen_cli_reference")


class TestLiveTreeParity:
    """The real CI gate: regenerated bytes must equal the committed file."""

    def test_config_reference_matches_committed_file(self) -> None:
        generated = gen_config_reference.generate()
        committed = CONFIG_REFERENCE_DOC.read_text(encoding="utf-8")
        assert generated == committed, (
            "docs/reference/configuration.md has drifted from src/athenaeum/config.py "
            "— run `python scripts/gen_config_reference.py` and commit the result."
        )

    def test_cli_reference_matches_committed_file(self) -> None:
        generated = gen_cli_reference.generate()
        committed = CLI_REFERENCE_DOC.read_text(encoding="utf-8")
        assert generated == committed, (
            "docs/reference/cli.md has drifted from athenaeum.cli.build_parser() "
            "— run `python scripts/gen_cli_reference.py` and commit the result."
        )


class TestGenerationIsDeterministic:
    """A gate that flaps is worse than no gate (issue athenaeum#1424's own
    determinism requirement) — regenerating twice must be byte-identical."""

    def test_config_reference_is_stable_across_runs(self) -> None:
        assert gen_config_reference.generate() == gen_config_reference.generate()

    def test_cli_reference_is_stable_across_runs(self) -> None:
        assert gen_cli_reference.generate() == gen_cli_reference.generate()

    def test_config_reference_is_independent_of_ambient_env(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        # An operator's leftover ATHENAEUM_* env var must not change a single
        # generated default — generate() clears them for its own duration.
        before = gen_config_reference.generate()
        monkeypatch.setenv("ATHENAEUM_CACHE_DIR", "/some/operator/leftover/value")
        monkeypatch.setenv("ATHENAEUM_MIN_CLUSTER_COHESION_SCOPES", "999")
        after = gen_config_reference.generate()
        assert before == after

    def test_config_reference_is_independent_of_system_local_timezone(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """AC3 (issue athenaeum#1527): the generated doc must not bake in
        the generating machine's local timezone. This differs from
        ``test_config_reference_is_stable_across_runs`` above in the axis
        it varies -- that test calls ``generate()`` twice with the SAME host
        state and proves repeated calls agree, which structurally cannot
        catch a value that is host-dependent but stable within one process
        (exactly this bug: every call on a given machine returned that
        machine's own zone, consistently). This test instead varies the
        host's resolved local timezone itself, across two very different
        zones, within a single process, and asserts the generated bytes are
        still identical.

        ``athenaeum.config._system_local_timezone()`` prefers the
        ``/etc/localtime`` symlink over ``TZ``, so on a host where that
        symlink resolves (most containers, including this test's), setting
        ``TZ`` alone does not change what it returns -- which is exactly why
        reproducing the original bug required actually repointing
        ``/etc/localtime``, not just the env var. To exercise the `TZ`-driven
        fallback branch portably (no root, no real host mutation), this
        patches ``os.path.realpath`` so the ``/etc/localtime`` lookup fails
        the way it already documents doing on "a container with no zoneinfo
        symlink" -- a real code path, not a synthetic one -- which makes
        ``TZ`` the live variable for the duration of this test.
        """
        real_realpath = os.path.realpath

        def _no_localtime_symlink(path: Any, *a: Any, **kw: Any) -> str:
            if os.fspath(path) == "/etc/localtime":
                raise OSError("simulated: no zoneinfo symlink for this test")
            return real_realpath(path, *a, **kw)

        monkeypatch.setattr(os.path, "realpath", _no_localtime_symlink)
        original_tz = os.environ.get("TZ")
        try:
            monkeypatch.setenv("TZ", "America/New_York")
            time.tzset()
            generated_new_york = gen_config_reference.generate()

            monkeypatch.setenv("TZ", "Pacific/Kiritimati")
            time.tzset()
            generated_kiritimati = gen_config_reference.generate()

            assert generated_new_york == generated_kiritimati
        finally:
            # monkeypatch restores the TZ env var at teardown, but not until
            # AFTER this function returns, and it never re-invokes tzset() --
            # so without this, the process-wide C library tz state would
            # stay pinned to whichever zone ran last, leaking into every
            # other test in this process. Restore both explicitly, in order,
            # before returning.
            if original_tz is None:
                monkeypatch.delenv("TZ", raising=False)
            else:
                monkeypatch.setenv("TZ", original_tz)
            time.tzset()


class TestGenerationIsGenuine:
    """Prove each generator actually reads the LIVE source rather than being
    a degenerate echo of the committed file — the same concern
    ``test_config_resolver_parity_generic.py`` and
    ``test_exit_codes_doc_parity.py`` raise about a derivation that could
    trivially always agree with the doc it's checked against.
    """

    def test_config_generator_reflects_a_new_resolver(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        from athenaeum import config as config_mod

        def resolve_throwaway_test_knob_for_parity_check(
            config: dict[str, Any] | None,
        ) -> str:
            """Resolve ``librarian.throwaway_test_knob_for_parity_check`` — a
            synthetic knob that exists only for this test."""
            if isinstance(config, dict):
                librarian_cfg = config.get("librarian") or {}
                if isinstance(librarian_cfg, dict):
                    raw = librarian_cfg.get("throwaway_test_knob_for_parity_check")
                    if isinstance(raw, str):
                        return raw
            return "default-value"

        monkeypatch.setattr(
            config_mod,
            "resolve_throwaway_test_knob_for_parity_check",
            resolve_throwaway_test_knob_for_parity_check,
            raising=False,
        )

        synthetic_source = (
            gen_config_reference.CONFIG_PY.read_text(encoding="utf-8")
            + "\n\n"
            + "def resolve_throwaway_test_knob_for_parity_check(config):\n"
            '    """Resolve ``librarian.throwaway_test_knob_for_parity_check`` — a\n'
            "    synthetic knob that exists only for this test.\n"
            '    """\n'
            "    return None\n"
        )
        real_config_py = gen_config_reference.CONFIG_PY

        class _FakePath:
            def read_text(self, encoding: str = "utf-8") -> str:
                return synthetic_source

            def __getattr__(self, name: str) -> Any:
                return getattr(real_config_py, name)

        monkeypatch.setattr(gen_config_reference, "CONFIG_PY", _FakePath())

        generated = gen_config_reference.generate()
        assert "resolve_throwaway_test_knob_for_parity_check" in generated
        assert "librarian.throwaway_test_knob_for_parity_check" in generated
        # And the REAL committed file (unaffected by the monkeypatch, since it
        # was generated before this test ever ran) must NOT already contain
        # it — proving this is genuinely new content the generator picked up
        # live, not something already baked into every run's output.
        committed = CONFIG_REFERENCE_DOC.read_text(encoding="utf-8")
        assert "resolve_throwaway_test_knob_for_parity_check" not in committed

    def test_cli_generator_reflects_a_new_flag(self, monkeypatch: pytest.MonkeyPatch) -> None:
        from athenaeum import cli as cli_mod

        real_build_parser = cli_mod.build_parser

        def _fake_build_parser():
            parser = real_build_parser()
            for action in parser._actions:
                import argparse

                if isinstance(action, argparse._SubParsersAction):
                    init_parser = action.choices["init"]
                    init_parser.add_argument(
                        "--throwaway-test-flag-for-parity-check",
                        action="store_true",
                        help="Synthetic flag that exists only for this test.",
                    )
            return parser

        monkeypatch.setattr(cli_mod, "build_parser", _fake_build_parser)

        generated = gen_cli_reference.generate()
        assert "--throwaway-test-flag-for-parity-check" in generated

        committed = CLI_REFERENCE_DOC.read_text(encoding="utf-8")
        assert "--throwaway-test-flag-for-parity-check" not in committed


class TestCuratedSetIsClosed:
    """``_CURATED`` in ``gen_config_reference.py`` is a small, justified
    exception list (resolvers whose signature/return shape makes generic
    runtime invocation unsafe or meaningless — see its own module-docstring
    comment). Pin its membership so a resolver cannot silently join it
    without this test changing too — the same discipline
    ``test_config_resolver_parity_generic.py`` applies to its own exclusion
    sets.
    """

    def test_curated_membership(self) -> None:
        assert set(gen_config_reference._CURATED.keys()) == {
            "resolve_cache_dir",
            "resolve_model",
            "resolve_recall_relevance_floor",
            "resolve_retention_policy",
            "resolve_retention_max_bytes",
            "resolve_retention_destination",
            "resolve_extra_intake_roots",
            "resolve_authority_manifest_path",
            "resolve_person_registry_root",
            "resolve_spend_accounting_timezone",
            "resolve_index_globs",
        }

    def test_curated_entries_are_real_resolvers(self) -> None:
        from athenaeum import config as config_mod

        for name in gen_config_reference._CURATED:
            assert hasattr(config_mod, name), f"{name} is not a real athenaeum.config resolver"


class TestCoverage:
    """AC1/AC3 sanity floors: the generators must have found the FULL
    surface, not silently degenerated to a handful of entries."""

    def test_every_resolver_in_config_py_is_documented(self) -> None:
        import ast

        src = gen_config_reference.CONFIG_PY.read_text(encoding="utf-8")
        tree = ast.parse(src)
        resolver_names = sorted(
            n.name
            for n in tree.body
            if isinstance(n, ast.FunctionDef) and n.name.startswith("resolve_")
        )
        assert len(resolver_names) >= 100, (
            f"only found {len(resolver_names)} resolve_* functions in config.py — "
            "expected 100+; enumeration may be broken"
        )
        committed = CONFIG_REFERENCE_DOC.read_text(encoding="utf-8")
        # `resolve_index_globs` bundles two independent yaml leaves and is
        # rendered as two headings, `` `resolve_index_globs (include_globs)` ``
        # and `` `resolve_index_globs (exclude_globs)` `` — a substring check
        # (rather than an exact `` `name` `` match) covers that shape too.
        missing = [name for name in resolver_names if name not in committed]
        assert not missing, f"resolve_* functions missing from configuration.md: {missing}"

    def test_config_reference_names_the_two_ac2_surfaces(self) -> None:
        committed = CONFIG_REFERENCE_DOC.read_text(encoding="utf-8")
        assert "librarian.corrections.fields" in committed
        assert '"shape"' in committed or "'shape'" in committed
        assert "writers" in committed
        assert "monotone" in committed

    def test_every_top_level_subcommand_is_documented(self) -> None:
        import argparse
        import sys

        sys.path.insert(0, str(REPO_ROOT / "src"))
        from athenaeum.cli import build_parser

        parser = build_parser()
        sub_action = next(
            a for a in parser._actions if isinstance(a, argparse._SubParsersAction)
        )
        top_level_names = sorted(sub_action.choices.keys())
        assert len(top_level_names) >= 50, (
            f"only found {len(top_level_names)} top-level subcommands — expected 50+; "
            "enumeration may be broken"
        )
        committed = CLI_REFERENCE_DOC.read_text(encoding="utf-8")
        missing = [name for name in top_level_names if f"`athenaeum {name}`" not in committed]
        assert not missing, f"top-level subcommands missing from cli.md: {missing}"
