# SPDX-License-Identifier: Apache-2.0
"""Raw-intake discovery + tier-0 passthrough primitives (issue athenaeum#545).

These three functions — :func:`discover_raw_files`, :func:`discover_auto_memory_files`,
and :func:`tier0_passthrough` — were previously module-level in
:mod:`athenaeum.librarian` (the L4 run-loop hub). Because they are shared
*inputs* to the run loop rather than part of it, the SCC siblings that need
them (``merge``, ``tiers``, ``batch``, ``status``, ``drain``) had to reach
BACK into ``librarian`` via function-local (deferred) imports — the
load-bearing back-edges that formed the librarian-centered import cycle.

Hoisting them DOWN to this leaf module lets every SCC sibling import them at
TOP level from here, so those deferred back-edges become unnecessary and are
removed (see issue athenaeum#545). :mod:`athenaeum.vecmath` (issue athenaeum#542) is the
precedent for this "hoist a shared primitive to a lower layer to dissolve a
cycle" move.

Layering: L2 primitive. Imports only leaf/service modules that do NOT import
any SCC member back — :mod:`athenaeum.models`, :mod:`athenaeum.config`,
:mod:`athenaeum.ephemeral`, :mod:`athenaeum._lint`, :mod:`athenaeum.schemas`,
:mod:`athenaeum.atomic_io`, and (issue athenaeum#797) :mod:`athenaeum.corrections`, a
peer L2 primitive. It must NEVER import ``librarian``, ``merge``,
``tiers``, ``pending_merges``, ``batch``, ``status``, ``retire``, or
``wiki_dedupe`` (that would re-introduce the cycle this module exists to
break). ``librarian`` re-exports these three names for backward compatibility,
so existing ``from athenaeum.librarian import discover_raw_files`` call sites
(and the public ``athenaeum.discover_raw_files`` re-export) keep working.

Issue athenaeum#797 (`docs/field-corrections.md` §3.1): a field-correction batch is
a `.jsonl` file living in the ORDINARY `raw/<source>/` tree — no reserved
subtree, no second discovery walk. :func:`discover_raw_files` recognizes one
by shape (its first line parses as a valid batch envelope, per
:func:`athenaeum.corrections.parse_batch_envelope`) and skips it — claimed by
the correction phase, which reads it directly rather than through this
function. Every OTHER `.jsonl` (malformed batch, unknown `schema_version`,
or a file that never claimed to be a batch at all) is ordinary intake,
exactly like a `.md` file — this is the only correction-shape knowledge this
function carries, and it must not carry any more than that (§3.1: "There is
no reserved subtree and no separate discovery function").
"""

from __future__ import annotations

import logging
import re
from collections.abc import Iterable
from datetime import date
from pathlib import Path
from typing import Any, cast

from athenaeum._lint import _strip_self_reference
from athenaeum.atomic_io import atomic_write_text
from athenaeum.compiled_exempt import load_exempt
from athenaeum.config import (
    load_config,
    resolve_ephemeral_scopes,
    resolve_extra_intake_roots,
    resolve_non_intake_sources,
    resolve_operational_markers,
    resolve_raw_file_max_bytes,
)
from athenaeum.corrections import parse_batch_envelope
from athenaeum.ephemeral import classify_ephemeral
from athenaeum.models import (
    AutoMemoryFile,
    EntityIndex,
    RawFile,
    WikiEntity,
    coerce_source_type,
    parse_asserter,
    parse_claim_kind,
    parse_deprecated,
    parse_frontmatter,
    parse_model,
    parse_on_behalf_of,
    parse_refines,
    parse_superseded_by,
    parse_supersedes,
    render_frontmatter,
    safe_source_ref,
    slugify,
    validity_bound_str,
)
from athenaeum.schemas import validate_wiki_meta

log = logging.getLogger(__name__)

# Raw file naming: {timestamp}-{uuid8}.md or (issue athenaeum#797) {timestamp}-{uuid8}.jsonl
# -- the same filename convention a correction batch uses
# (docs/field-corrections.md §3.1), widened here so a batch's timestamp/uuid
# still parse like any other raw-intake file. The extension is NOT what
# decides whether a .jsonl is claimed by the correction phase -- shape
# (parse_batch_envelope on the first line) decides that, in the caller below.
RAW_FILE_RE = re.compile(r"^(\d{8}T\d{6}Z?)-([0-9a-f]{8})\.(?:md|jsonl)$", re.IGNORECASE)

# Auto-memory file naming: <prefix>_<slug>.md where prefix is one of
# feedback|project|reference|user|Recall. Slug is underscore-separated
# lowercase, but the regex only constrains the prefix — typo bodies
# (e.g. project_foo_bar.md) must still match so C2 clustering
# can dedupe them downstream. The ``Recall`` prefix is capitalized in
# production (see raw/auto-memory/.../Recall_architecture.md); lowercase
# ``recall_`` is also accepted defensively.
AUTO_MEMORY_FILE_RE = re.compile(
    r"^(feedback|project|reference|user|Recall|recall)_(.+)\.md$"
)

# Filenames to skip in auto-memory scope scan. ``MEMORY.md`` is the
# per-scope curated index generated by build-per-scope-memory-index.py
# (mirrors search.py's _INTAKE_SKIP_NAMES contract). Non-.md files are
# already filtered by the glob, but ``_migration-log.jsonl`` lives at
# raw/auto-memory/ root — excluded by the directory-only iteration below.
_AUTO_MEMORY_SKIP_NAMES: frozenset[str] = frozenset({"MEMORY.md"})


def discover_auto_memory_files(
    knowledge_root: Path | None = None,
    config: dict[str, object] | None = None,
) -> list[AutoMemoryFile]:
    """Find all auto-memory intake files under ``raw/auto-memory/<scope>/``.

    Uses :func:`resolve_extra_intake_roots` to pick up the auto-memory
    root from config (``recall.extra_intake_roots``) — does NOT hard-code
    the path. This keeps the config surface single-sourced with the
    recall index builder.

    Returns a list of :class:`AutoMemoryFile` records sorted by
    ``(scope, filename)``. ``MEMORY.md`` files and non-directory entries
    at the auto-memory root (e.g. ``_migration-log.jsonl``) are excluded.
    The ``_unscoped/`` directory is included as a scope alongside named
    scopes — its files are first-class memories, not metadata.
    """
    if knowledge_root is None:
        knowledge_root = Path.home() / "knowledge"

    # resolve_extra_intake_roots returns absolute paths for every
    # configured intake root; in the default config the only entry is
    # raw/auto-memory but callers can configure more, so we iterate all.
    roots = resolve_extra_intake_roots(knowledge_root, config=config)
    if not roots:
        return []

    # Issue athenaeum#278: resolve the ephemeral/operational classifier inputs once.
    # An ephemeral-scope OR ``ephemeral: true``-flagged intake is dropped
    # HERE -- the cleanest choke point -- so it is never clustered or
    # materialized into a durable ``wiki/auto-*.md`` page. Drops are logged
    # with their reason; the raw file stays on disk (the move-then-retire
    # pass only touches members that landed in a wiki entry), so a dropped
    # file is simply re-evaluated (and re-dropped) idempotently next run.
    resolved_config = config if config is not None else load_config(knowledge_root)
    ephemeral_scopes = resolve_ephemeral_scopes(resolved_config)
    operational_markers = resolve_operational_markers(resolved_config)
    dropped_ephemeral = 0

    files: list[AutoMemoryFile] = []
    for root in roots:
        if not root.is_dir():
            continue
        # Directory-only iteration at the root level. This is how we
        # skip _migration-log.jsonl and any other non-scope sibling
        # files without relying on the .md glob alone.
        for scope_dir in sorted(root.iterdir()):
            if not scope_dir.is_dir():
                continue
            scope = scope_dir.name
            for fpath in sorted(scope_dir.glob("*.md")):
                if fpath.name in _AUTO_MEMORY_SKIP_NAMES:
                    continue
                m = AUTO_MEMORY_FILE_RE.match(fpath.name)
                if not m:
                    # Defensive: anything not matching the auto-memory
                    # convention is skipped here. Entity-schema files
                    # (<timestamp>-<uuid8>.md) naturally fall through
                    # because they lack the prefix.
                    continue
                memory_type = m.group(1).lower()
                try:
                    text = fpath.read_text(encoding="utf-8")
                except (OSError, UnicodeDecodeError):
                    continue
                meta, _body = parse_frontmatter(text)
                # Issue athenaeum#278: drop ephemeral/operational intake before it can
                # be clustered + merged into a permanent wiki entity.
                drop_reason = classify_ephemeral(
                    scope,
                    meta,
                    _body,
                    ephemeral_scopes=ephemeral_scopes,
                    operational_markers=operational_markers,
                )
                if drop_reason is not None:
                    dropped_ephemeral += 1
                    log.info(
                        "auto-memory: dropping ephemeral intake %s - %s",
                        fpath,
                        drop_reason,
                    )
                    continue
                name = str(meta.get("name", "")) if meta else ""
                description = str(meta.get("description", "")) if meta else ""
                origin_session_id = meta.get("originSessionId") if meta else None
                if origin_session_id is not None:
                    origin_session_id = str(origin_session_id)
                origin_turn_raw = meta.get("originTurn") if meta else None
                origin_turn: int | None
                try:
                    # origin_turn_raw is an arbitrary YAML scalar (object);
                    # int() rejects that statically even though at runtime
                    # it accepts str/float/bool/etc. Any type mismatch not
                    # covered by int()'s overloads still raises TypeError,
                    # caught below exactly as before.
                    origin_turn = (
                        int(cast(str, origin_turn_raw))
                        if origin_turn_raw is not None
                        else None
                    )
                except (TypeError, ValueError):
                    origin_turn = None
                sources_raw = meta.get("sources") if meta else None
                if isinstance(sources_raw, list):
                    sources = [str(s) for s in sources_raw]
                else:
                    sources = []
                # Issue athenaeum#260 (slice A of athenaeum#259): origin-traced provenance.
                # Missing source_type defaults to ``inferred``; source_ref is
                # the ultimate reference and is never this file's own name.
                source_type = coerce_source_type(
                    meta.get("source_type") if meta else None
                )
                # Guard the explicit path: a frontmatter source_ref that is a
                # raw filename (or any ``.md``) is rejected to "" rather than
                # cited as the ultimate source (athenaeum#260 invariant).
                source_ref = safe_source_ref(
                    meta.get("source_ref") if meta else None, ""
                )
                # Lane 1 / athenaeum#167: declared refines/supersedes relationships.
                # Malformed entries raise — surfacing the bad file rather
                # than silently dropping the declaration.
                try:
                    refines = parse_refines(meta if meta else None)
                    supersedes = parse_supersedes(meta if meta else None)
                except ValueError as exc:
                    log.warning(
                        "auto-memory %s: invalid refines/supersedes (%s); "
                        "treating as empty",
                        fpath,
                        exc,
                    )
                    refines = []
                    supersedes = []
                # Issue athenaeum#173 / athenaeum#181: drop refines/supersedes self-references.
                refines, supersedes = _strip_self_reference(
                    name, refines, supersedes, fpath
                )
                # Issue athenaeum#191: non-destructive inactive markers.
                meta_for_markers = meta if meta else None
                files.append(
                    AutoMemoryFile(
                        path=fpath,
                        origin_scope=scope,
                        memory_type=memory_type,
                        name=name,
                        description=description,
                        origin_session_id=origin_session_id,
                        origin_turn=origin_turn,
                        sources=sources,
                        refines=refines,
                        supersedes=supersedes,
                        superseded_by=parse_superseded_by(meta_for_markers),
                        deprecated=parse_deprecated(meta_for_markers),
                        source_type=source_type,
                        source_ref=source_ref,
                        # Issue athenaeum#326: channel-split provenance annotations.
                        model=parse_model(meta_for_markers),
                        on_behalf_of=parse_on_behalf_of(meta_for_markers),
                        asserter=parse_asserter(meta_for_markers),
                        # Issue athenaeum#327: epistemic claim kind (fail-open when
                        # absent/unrecognized → "" unclassified).
                        claim_kind=parse_claim_kind(meta_for_markers),
                        # Issue athenaeum#308: claim-level temporal validity bounds.
                        valid_from=validity_bound_str(meta_for_markers, "valid_from"),
                        valid_until=validity_bound_str(meta_for_markers, "valid_until"),
                    )
                )
    if dropped_ephemeral:
        log.info(
            "auto-memory: dropped %d ephemeral/operational intake file(s) "
            "before clustering (issue athenaeum#278)",
            dropped_ephemeral,
        )
    return files


def _is_claimed_correction_batch(fpath: Path) -> bool:
    """True when *fpath* is a `.jsonl` whose first line is a valid batch
    envelope (issue athenaeum#797, `docs/field-corrections.md` §3.1) — claimed by
    the correction phase, which reads it directly, rather than by this
    discovery function.

    Only the FIRST LINE is read (a batch may carry thousands of records;
    reading the whole file just to decide visibility defeats the streaming
    point of the format). Any read failure (permission error, bad encoding)
    or an empty first line (a zero-byte file) means "not a valid envelope" —
    conservatively falls through to ordinary intake, never silently
    disappears.
    """
    try:
        with fpath.open("r", encoding="utf-8") as fh:
            first_line = fh.readline()
    except (OSError, UnicodeDecodeError):
        return False
    if not first_line.strip():
        return False
    return parse_batch_envelope(first_line) is not None


def discover_raw_files(
    raw_root: Path, config: dict[str, Any] | None = None
) -> list[RawFile]:
    """Find all raw intake files, sorted by timestamp.

    Issue athenaeum#843: ``config`` threads the operator's
    ``librarian.non_intake_sources`` exclusion list (mirrors how
    :func:`athenaeum.tiers.tier1_programmatic_match` already takes ``config``
    for its own operator-tuned exclusion list). A source directory named
    there is skipped WHOLE, before any glob work — the general form of the
    hardcoded ``answers`` skip below. ``None`` (the default, preserving the
    pre-athenaeum#843 call signature) excludes nothing.

    Issue athenaeum#797 (`docs/field-corrections.md` §3.1): globs `*.jsonl` in
    addition to `*.md` so a correction batch — which lives in this SAME
    ordinary `raw/<source>/` tree, no reserved subtree — is visible at all.
    A `.jsonl` is skipped (claimed by the correction phase instead of being
    appended here) ONLY when its first line is a valid batch envelope
    (:func:`athenaeum.corrections.parse_batch_envelope`); every other
    `.jsonl` — not JSON, valid JSON but not `record: "batch"`, an unknown
    `schema_version`, or a zero-byte file — is ordinary intake, appended
    below exactly like a `.md` file. This is deliberate: a malformed batch
    must still reach ordinary intake (reasoning classifies its raw text),
    never disappear.

    Issue athenaeum#898: every returned :class:`RawFile` carries
    ``max_content_bytes`` resolved from ``config`` via
    :func:`athenaeum.config.resolve_raw_file_max_bytes` (env > yaml >
    default), so a first read of ``.content`` anywhere downstream enforces
    the per-file byte bound uniformly — this is the ONE place that resolves
    it, not a per-call-site knob.
    """
    files: list[RawFile] = []
    if not raw_root.exists():
        return files

    non_intake = resolve_non_intake_sources(config)
    raw_file_max_bytes = resolve_raw_file_max_bytes(config)
    # Issue athenaeum#903: a `retain`-dispositioned file is a long-lived SOURCE
    # DOCUMENT, marked compiled-exempt in the manifest under the knowledge root.
    # Filtering here — inside discovery itself rather than at any one call site
    # — is what makes "skipped by discovery on EVERY subsequent run" true for
    # the entity loop, the drain backlog count and `status` alike, without
    # touching a single caller. Fails open to an empty set.
    exempt_refs = load_exempt(raw_root.parent)

    for source_dir in sorted(raw_root.iterdir()):
        if not source_dir.is_dir():
            continue
        source = source_dir.name
        # Issue athenaeum#843: an operator-excluded source dir holds a tool's
        # own operational artifacts, not memory content. Skip it at the source
        # level like `answers` below — before any glob/regex work, so a
        # directory of multi-megabyte logs costs one set lookup, not a walk.
        if source in non_intake:
            continue
        # Issue athenaeum#414: answer fragments under raw/answers/ are resolution
        # OUTPUT, not new intake. Re-discovering them feeds already-settled
        # rulings back through tier1-2 classification and tier4 contradiction
        # escalation, so the same ruling re-surfaces as fresh pending
        # questions on every subsequent run. Skip them at the source level,
        # before any tier classification can re-escalate them.
        if source == "answers":
            continue
        candidates = sorted(
            {*source_dir.glob("*.md"), *source_dir.glob("*.jsonl")}
        )
        for fpath in candidates:
            if fpath.name == ".gitkeep":
                continue
            # Issue athenaeum#903 (`retain`): compiled-exempt — a preserved source
            # document. Still on disk, never offered to the tiers again. The key
            # is ``RawFile.ref`` (``source/filename``), the same identifier the
            # audit ledger uses.
            if exempt_refs and f"{source}/{fpath.name}" in exempt_refs:
                continue
            if fpath.suffix.lower() == ".jsonl" and _is_claimed_correction_batch(
                fpath
            ):
                # Claimed by the correction phase (§3.1) -- not ordinary
                # intake, and NOT a second discovery walk: the correction
                # phase reads this exact file directly by path/shape, it is
                # simply not appended to the list this function returns.
                continue
            m = RAW_FILE_RE.match(fpath.name)
            if m:
                files.append(
                    RawFile(
                        path=fpath,
                        source=source,
                        timestamp=m.group(1),
                        uuid8=m.group(2),
                        max_content_bytes=raw_file_max_bytes,
                    )
                )
            else:
                files.append(
                    RawFile(
                        path=fpath,
                        source=source,
                        timestamp="",
                        uuid8="",
                        max_content_bytes=raw_file_max_bytes,
                    )
                )
    return files


def tier0_passthrough(
    raw: RawFile,
    index: EntityIndex,
    wiki_root: Path,
    valid_types: list[str],
    dry_run: bool = False,
) -> WikiEntity | None:
    """Promote a pre-structured raw-intake file to wiki/ verbatim.

    Some upstream producers (e.g. ``generate_warm_wiki.py``, contact-sync
    scripts) emit raw-intake markdown that is *already* in valid wiki
    schema — has ``uid``, ``type``, ``name``, plus rich custom-namespace
    frontmatter (``relationship:``, ``exclude:``, ``apollo_*``,
    ``current_title``, ``linkedin_url``, etc.). Sending such files through
    Tier 2/3 is wasteful (one Haiku + one Sonnet call per file) AND lossy:
    the LLM-driven path rebuilds frontmatter from a fixed allowlist and
    drops any field outside it.

    This passthrough writes the raw frontmatter + body to ``wiki/``
    byte-for-byte, only stamping ``created`` (if missing) and ``updated``
    to today. No classification runs; the index is updated so later raw
    files in the same pipeline can match against it.

    Returns the new :class:`WikiEntity` on success, or ``None`` if the
    raw is unstructured / ineligible (caller should fall through to
    Tier 1/2/3). Eligibility gate: frontmatter parses, ``uid``/``type``/
    ``name`` are non-empty, ``type`` is in the schema's allowlist, and the
    uid is not already present in the index (idempotent re-runs).
    """
    meta, body = parse_frontmatter(raw.content)
    if not meta:
        return None
    uid = str(meta.get("uid", "") or "").strip()
    etype = str(meta.get("type", "") or "").strip()
    name = str(meta.get("name", "") or "").strip()
    if not uid or not etype or not name:
        return None
    if etype not in valid_types:
        return None
    if index.get_by_uid(uid) is not None:
        return None

    today = date.today().isoformat()
    if not meta.get("created"):
        meta["created"] = today
    meta["updated"] = today

    filename = f"{uid}-{slugify(name)}.md"
    out_path = wiki_root / filename
    if out_path.exists():
        # Filename collision with a different uid would be a real bug,
        # but a same-uid existing file is already covered by the index
        # check above. Defer to Tier 1/2/3 rather than overwrite blindly.
        return None

    aliases_raw = meta.get("aliases") or []
    tags_raw = meta.get("tags") or []
    # meta is dict[str, object] (arbitrary YAML scalars). aliases/tags are
    # documented as list-shaped frontmatter fields, but the prior runtime
    # behavior tolerated any iterable (e.g. a bare string would iterate
    # per-character) and only raised TypeError for genuinely non-iterable
    # truthy values. Narrow to Iterable (not list) to keep that behavior
    # exactly; each element is coerced via str() below regardless.
    assert isinstance(aliases_raw, Iterable)
    assert isinstance(tags_raw, Iterable)
    entity = WikiEntity(
        uid=uid,
        type=etype,
        name=name,
        aliases=[str(a) for a in aliases_raw if a],
        access=str(meta.get("access", "internal")),
        tags=[str(t) for t in tags_raw if t],
        created=str(meta.get("created", today)),
        updated=str(meta.get("updated", today)),
        body=body,
    )

    # Validate frontmatter against the Pydantic schema before write. This
    # is the schema gate for the byte-for-byte passthrough — malformed
    # custom-namespace fields are still accepted (extra="allow"), but the
    # uid/type/name contract is enforced. Raises pydantic.ValidationError
    # on failure; caller treats that as a real bug, not a fall-through.
    validate_wiki_meta(meta)

    if dry_run:
        return entity

    atomic_write_text(
        out_path,
        render_frontmatter(meta) + "\n" + body,
    )
    index.register(entity)
    return entity
