#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Generate the subject/claimed_scope-annotated sibling of the two shadow-parity
eval corpora (issue athenaeum#1483).

**Why this exists.** The 2026-09-04 shadow-parity run (measurements/shadow-parity-2026-09-04.md)
returned NO-GO because `VERDICT_CONTRADICTION` was unreachable: `subject` and
`scope` are ENFORCED separator dimensions
(:mod:`athenaeum.dimensions`), and neither `subject` nor `claimed_scope`
occurs anywhere in `tests/evals/data/{detector,resolver}/cases.yaml` -- so
`subject` was UNKNOWN on every pair, which routes `compare_pages`
(`src/athenaeum/comparator.py`) to `VERDICT_UNDERDETERMINED` before it can
ever reach a contradiction verdict.

**This script does NOT edit either `cases.yaml` in place** (the C4 detector/
resolver evals assert against those files byte-for-byte). It reads both,
computes annotated frontmatter, and writes a SIBLING file next to each:

    tests/evals/data/detector/cases.subject-scope.yaml
    tests/evals/data/resolver/cases.subject-scope.yaml

**The label-blind annotation rule (issue athenaeum#1483, stated before any run
was made against this fixture):**

    subject = the shared stem of the cluster's member ``name:`` values.

Concretely, per cluster (case): take every member's ``frontmatter.name``,
compute their longest common string prefix, then trim that prefix back to
the last complete ``-``-delimited segment (so a prefix that stops mid-word,
e.g. ``"headcount-j"`` from ``headcount-jan``/``headcount-jun``, becomes the
whole-word ``"headcount"``, not the partial fragment) -- UNLESS the raw
prefix already exactly equals one of the member names (a name that is
itself a prefix of the other, e.g. ``standup-time`` / ``standup-time-updated``),
in which case no trimming is needed. If every member's name shares no
common prefix at all (empty stem -- e.g. ``client-weekly-sync`` /
``internal-monthly``), each member keeps its OWN name as its `subject`
coordinate, so the pair's subject values differ and `compare_identity`
reads UNKNOWN (never DISJOINT -- `compare_identity` only returns DISJOINT
for `ratified=True`, which this harness never sets), exactly preserving
this pair's pre-annotation behaviour.

This rule is applied identically regardless of the case's `outcome_class`
-- it is a pure function of the member `name:` strings, so it cannot be
tuned toward (or away from) any particular verdict. Verified: it yields
`subject` EQUAL on `standup_time` (`outcome_class: contradict`) and on
`invoice_cadence_refinement` (`outcome_class: pass`) alike -- see this
module's own test, `tests/test_annotate_shadow_parity_subject_scope.py`.

**`claimed_scope` uses the SAME derived stem value as `subject`, per
cluster.** The issue names a rule for `subject` only; `scope`'s
`null_means=universal` already makes a both-absent pair read EQUAL once
`athenaeum#1483`'s `_null_relation` decision lands (`src/athenaeum/dimensions.py`),
so `claimed_scope` needed no annotation at all to become reachable --
stamping it here is for AC2's literal "carrying subject and claimed_scope
coordinates" and for inspectability (AC3), not because it changes
reachability. Reusing the identical mechanical derivation (rather than
inventing a second, unstated rule) keeps this fully auditable: nothing
about `claimed_scope`'s value is hand-chosen per case.

Run: ``python scripts/annotate_shadow_parity_subject_scope.py``
(idempotent -- re-running overwrites the two output files with the same
content given the same two source files).
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent

CORPORA = (
    REPO_ROOT / "tests/evals/data/detector/cases.yaml",
    REPO_ROOT / "tests/evals/data/resolver/cases.yaml",
)

HEADER = """\
# GENERATED by scripts/annotate_shadow_parity_subject_scope.py -- DO NOT HAND-EDIT.
# Sibling of {source_name} (issue athenaeum#1483) -- {source_name} itself is NOT
# modified; the C4 detector/resolver evals assert against it directly.
#
# Every member's frontmatter below is byte-identical to {source_name} except
# for two added keys, `subject` and `claimed_scope`, stamped by the
# label-blind rule recorded in this script's module docstring:
#
#     subject = the shared stem of the cluster's member `name:` values,
#     applied identically regardless of outcome_class.
#
# claimed_scope reuses the same derived stem (see the module docstring for
# why that coordinate needed no annotation to become reachable).
#
# Regenerate with: python scripts/annotate_shadow_parity_subject_scope.py
"""


def shared_stem(names: list[str]) -> str:
    """The label-blind `subject` derivation: shared stem of *names*, or ``""``
    if the names have no common prefix at all (see module docstring)."""
    if not names:
        return ""
    raw = os.path.commonprefix(names)
    if not raw:
        return ""
    if raw.endswith("-"):
        return raw.rstrip("-")
    if raw in names:
        # raw is itself one of the full names (that name is a prefix of the
        # other) -- no truncation needed.
        return raw
    if "-" in raw:
        # Truncate a mid-word prefix back to the last complete segment.
        return raw.rsplit("-", 1)[0]
    return raw


def annotate_case(case: dict[str, Any]) -> dict[str, Any]:
    """Return a COPY of *case* with `subject`/`claimed_scope` stamped onto
    every member's frontmatter, per the module docstring's rule."""
    members = case.get("members", [])
    names = [str(m["frontmatter"]["name"]) for m in members]
    stem = shared_stem(names)

    new_members = []
    for member, name in zip(members, names):
        new_fm = dict(member["frontmatter"])
        value = stem if stem else name
        new_fm["subject"] = value
        new_fm["claimed_scope"] = value
        new_member = dict(member)
        new_member["frontmatter"] = new_fm
        new_members.append(new_member)

    new_case = dict(case)
    new_case["members"] = new_members
    return new_case


def annotate_corpus(source: Path) -> tuple[Path, str]:
    raw = yaml.safe_load(source.read_text(encoding="utf-8")) or []
    annotated = [annotate_case(case) for case in raw]
    body = yaml.dump(annotated, sort_keys=False, default_flow_style=False, allow_unicode=True)
    dest = source.with_name(source.stem + ".subject-scope" + source.suffix)
    content = HEADER.format(source_name=source.name) + "\n" + body
    return dest, content


def main() -> int:
    for source in CORPORA:
        dest, content = annotate_corpus(source)
        dest.write_text(content, encoding="utf-8")
        print(f"wrote {dest.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
